/** User-supplied Grigoriev scenes, identified against the magazine's captions.
 * Chapter links and summaries refer to the local Garnett text, not the artwork's dating.
 */
export const SCENE_SOURCE = 'https://www.tretyakovgallerymagazine.com/articles/4-2021-73/amazing-mixture-good-and-evil';

export const ILLUSTRATED_SCENES = [
  {
    id: 'passionate-heart',
    title: 'The confession of a passionate heart',
    artworkTitle: 'The Confession of an Ardent Heart',
    file: 'passionate-heart.jpg',
    afterCharacter: 'dmitri',
    chapter: 'b03-c03',
    people: ['dmitri', 'alyosha'],
    description: 'In the garden, Dmitri pours out his heart to Alyosha. Poetry gives way to confession: his longing for beauty, his shame, and the story of the two women between whom his life is divided.',
    looking: 'The luminous tree fills the space between the brothers; their dark figures sit apart beneath it.',
    note: 'Dmitri trusts Alyosha with the contradictions that others will later flatten into a story of guilt. The confession continues through the next two chapters.',
    alt: 'Alyosha and Dmitri sit apart beneath a luminous tree, with village roofs and a crescent moon beyond.',
  },
  {
    id: 'over-the-brandy',
    title: 'Over the brandy',
    artworkTitle: 'Drinking Cognac',
    file: 'over-the-brandy.jpg',
    afterCharacter: 'fyodor',
    chapter: 'b03-c08',
    people: ['fyodor', 'ivan', 'alyosha', 'smerdyakov'],
    description: 'At the family table, Fyodor turns the conversation toward God and immortality. Ivan denies what Alyosha affirms. Drink loosens the father’s tongue, and his mockery of the past wounds the sons in front of him.',
    looking: 'The huge samovar crowds the table, while faces and bodies pull the gathering in different directions.',
    note: 'Questions about belief are already questions about how these people treat one another. The family’s cruelty gives the argument its force.',
    alt: 'The Karamazov household gathers around a large samovar in a crowded red interior.',
  },
  {
    id: 'both-together',
    title: 'Both together',
    artworkTitle: 'Both Together',
    file: 'both-together.jpg',
    afterCharacter: 'katerina',
    chapter: 'b03-c10',
    people: ['katerina', 'grushenka', 'alyosha'],
    description: 'Alyosha finds Katerina and Grushenka together. An apparent reconciliation turns into an exchange of humiliations: a hand kissed, a kiss withheld, and Dmitri’s future hanging between them.',
    looking: 'The women occupy the sofa while Alyosha stands behind: he can witness the contest, but cannot prevent it.',
    note: 'What begins as generous courtesy exposes wounded pride. Alyosha sees how quickly the wish to be loved becomes the wish to humiliate.',
    alt: 'Katerina and Grushenka sit on a striped sofa while Alyosha stands quietly behind them.',
  },
  {
    id: 'smerdyakov-guitar',
    title: 'Smerdyakov with a guitar',
    artworkTitle: 'Smerdyakov with a Guitar',
    file: 'smerdyakov-guitar.jpg',
    afterCharacter: 'smerdyakov',
    chapter: 'b05-c02',
    people: ['smerdyakov', 'alyosha'],
    description: 'Searching for Dmitri, Alyosha overhears Smerdyakov singing to Marya Kondratyevna. The cook’s talk is full of resentment and disdain. When Alyosha interrupts, he learns where to look for Ivan.',
    looking: 'Follow the guitar toward Marya on the bench, then notice Alyosha standing just outside their conversation.',
    note: 'The servant at the edge of the family has a voice of his own. His resentment matters long before the brothers understand how closely he has been listening.',
    alt: 'Smerdyakov plays a guitar beside Marya Kondratyevna on a garden bench; Alyosha stands at the edge.',
  },
  {
    id: 'alyosha-snegiryov',
    title: 'Alyosha and Captain Snegiryov',
    artworkTitle: 'Alyosha and Captain Snegiryov',
    file: 'alyosha-snegiryov.jpg',
    afterCharacter: 'zossima',
    chapter: 'b04-c07',
    people: ['alyosha', 'snegiryov'],
    description: 'Out in the open air, the captain tells Alyosha how Dmitri’s cruelty humiliated him before his son. Two hundred roubles seem to promise a new life for the family—until wounded pride makes him stamp the notes into the earth.',
    looking: 'The captain’s fingers rise to his mouth; beside him, Alyosha’s lowered eyes make the encounter unusually intimate.',
    note: 'The money could rescue the household, but accepting it feels like another humiliation. Alyosha has to learn that help must leave room for dignity.',
    alt: 'Alyosha stands beside Captain Snegiryov, who holds his fingers to his mouth, with the town behind them.',
  },
  {
    id: 'delirium',
    title: 'Delirium',
    artworkTitle: 'Delirium',
    file: 'delirium.jpg',
    afterCharacter: 'grushenka',
    chapter: 'b08-c08',
    people: ['dmitri', 'grushenka'],
    description: 'At Mokroye, the revelry grows feverish. Two girls dressed as bears tumble before the crowd while Dmitri and Grushenka imagine a life together. Before the night is over, the officers arrive to arrest him.',
    looking: 'The tumbling bear costumes and crowded faces turn the celebration into a scene of almost uncontainable motion.',
    note: 'Dmitri and Grushenka briefly imagine a future together. The arrest interrupts that possibility, turning a night of release into the beginning of his trial.',
    alt: 'A crowded celebration with musicians and two performers dressed as bears tumbling on the floor.',
  },
] as const;
