/** User-supplied Grigoriev scenes, identified against the magazine's captions.
 * Chapter links and summaries refer to the local Garnett text, not the artwork's dating.
 */
export const SCENE_SOURCE = 'https://www.tretyakovgallerymagazine.com/articles/4-2021-73/amazing-mixture-good-and-evil';

export const ILLUSTRATED_SCENES = [
  {
    id: 'passionate-heart',
    title: 'The confession of a passionate heart',
    artworkTitle: 'The Confession of an Ardent Heart',
    file: 'passionate-heart.jpg',
    afterCharacter: 'dmitri',
    chapter: 'b03-c03',
    people: ['dmitri', 'alyosha'],
    description: 'In the garden, Dmitri pours out his heart to Alyosha. Poetry gives way to confession: his longing for beauty, his shame, and the story of the two women between whom his life is divided.',
    note: 'Their conversation continues through the next two chapters.',
    alt: 'Alyosha and Dmitri sit apart beneath a luminous tree, with village roofs and a crescent moon beyond.',
  },
  {
    id: 'over-the-brandy',
    title: 'Over the brandy',
    artworkTitle: 'Drinking Cognac',
    file: 'over-the-brandy.jpg',
    afterCharacter: 'fyodor',
    chapter: 'b03-c08',
    people: ['fyodor', 'ivan', 'alyosha', 'smerdyakov'],
    description: 'At the family table, Fyodor turns the conversation toward God and immortality. Ivan denies what Alyosha affirms. Drink loosens the father’s tongue, and his mockery of the past wounds the sons in front of him.',
    note: 'A family gathering on the edge of a quarrel.',
    alt: 'The Karamazov household gathers around a large samovar in a crowded red interior.',
  },
  {
    id: 'both-together',
    title: 'Both together',
    artworkTitle: 'Both Together',
    file: 'both-together.jpg',
    afterCharacter: 'katerina',
    chapter: 'b03-c10',
    people: ['katerina', 'grushenka', 'alyosha'],
    description: 'Alyosha finds Katerina and Grushenka together. An apparent reconciliation turns into an exchange of humiliations: a hand kissed, a kiss withheld, and Dmitri’s future hanging between them.',
    note: 'Courtesy becomes a contest neither woman will forget.',
    alt: 'Katerina and Grushenka sit on a striped sofa while Alyosha stands quietly behind them.',
  },
  {
    id: 'smerdyakov-guitar',
    title: 'Smerdyakov with a guitar',
    artworkTitle: 'Smerdyakov with a Guitar',
    file: 'smerdyakov-guitar.jpg',
    afterCharacter: 'smerdyakov',
    chapter: 'b05-c02',
    people: ['smerdyakov', 'alyosha'],
    description: 'Searching for Dmitri, Alyosha overhears Smerdyakov singing to Marya Kondratyevna. The cook’s talk is full of resentment and disdain. When Alyosha interrupts, he learns where to look for Ivan.',
    note: 'An overheard conversation in the neighbouring garden.',
    alt: 'Smerdyakov plays a guitar beside Marya Kondratyevna on a garden bench; Alyosha stands at the edge.',
  },
  {
    id: 'alyosha-snegiryov',
    title: 'Alyosha and Captain Snegiryov',
    artworkTitle: 'Alyosha and Captain Snegiryov',
    file: 'alyosha-snegiryov.jpg',
    afterCharacter: 'zossima',
    chapter: 'b04-c07',
    people: ['alyosha', 'snegiryov'],
    description: 'Out in the open air, the captain tells Alyosha how Dmitri’s cruelty humiliated him before his son. Two hundred roubles seem to promise a new life for the family—until wounded pride makes him stamp the notes into the earth.',
    note: 'Kindness cannot simply buy back a person’s dignity.',
    alt: 'Alyosha stands beside Captain Snegiryov, who holds his fingers to his mouth, with the town behind them.',
  },
  {
    id: 'delirium',
    title: 'Delirium',
    artworkTitle: 'Delirium',
    file: 'delirium.jpg',
    afterCharacter: 'grushenka',
    chapter: 'b08-c08',
    people: ['dmitri', 'grushenka'],
    description: 'At Mokroye, the revelry grows feverish. Two girls dressed as bears tumble before the crowd while Dmitri and Grushenka imagine a life together. Before the night is over, the officers arrive to arrest him.',
    note: 'A moment of happiness, just before the accusation.',
    alt: 'A crowded celebration with musicians and two performers dressed as bears tumbling on the floor.',
  },
] as const;
